### ISSUE TITLE
how to change Device Key ?

### ISSUE THREAD

**Issue by jyhfeng** [XternA/spide-network#1] opened 2024-04-18 06:38 UTC
when I run 
"sudo podman run -d --restart unless-stopped --name spide xterna/spide-network"
in different machine
but I always get the same key, and the key is used

**Comment by XternA** [comment] 2024-04-19 01:20
Thanks for raising this.

So, I've done some experimenting around. Unfortunately, it's not possible to view the actual source code to see how the device key is generated as the GH page is not available and the source is closed.

Here is what I can confirm after running the experiment on multiple machine instances:

1. Not sure how they decide the device key is given but if you run the same distro, regardless of the machine instance, it will be the same device key. 
    - This could be 2 separate machines running Ubuntu 20.04. Device key will be identical.
2. I ran the command to get the device key from the container, which uses alpine Linux. device key are the same across machines.
3. I downloaded the application separately and run it standalone, without container, device key is different to that of the container.
    - I do the same for another machine, device key is the same if same distro.

This means that we can conclude the following, assuming you and I who runs either:

1. The container version or the standalone version, if we use Windows, our keys will be `xyz`. 
2. If we both run Ubuntu Linux, our device key will be `abc`.
3. If we both use container version, our device key will be `123`.

So until there is a solution to this, or the official release/more updates from Spide Network themselves, it will seem like we're stuck with having one device registerable for the time being.

My instant is that the device key is tied to the OS distro type. The only way to say have two machines registered is one running as a container, and another one running standalone. 

Hope this makes sense.

**Comment by engageub** [comment] 2024-05-06 09:01
Hello,
I do not wish to create a new docker image again and maintain. So, I am giving you steps to resolve this.

You are creating the machine Id when the image is created. So it will be used each time.
Change the last CMD command to the following.

```
CMD if [ ! -f "output.txt" ]; then cat /dev/urandom | LC_ALL=C tr -dc 'a-f0-9' | dd bs=1 count=32 2>/dev/null > /etc/machine-id; fi && ./spide 2>&1 | tee -a output.txt
```

The above command will create new ID whenever the container starts. 

Remove the following command from code.

```
RUN touch /etc/machine-id
```

The output is stored to output.txt file. To get the device id, "docker exec" command can be used to grep the logs.

Let me know if you need further clarification. 


Thank you

**Comment by engageub** [comment] 2024-05-06 14:02
The above code has been updated. You just have to replace as mentioned.

**Comment by XternA** [comment] 2024-05-06 15:00
> Hello, I do not wish to create a new docker image again and maintain. So, I am giving you steps to resolve this.
> 
> You are creating the machine Id when the image is created. So it will be used each time. Change the last CMD command to the following.
> 
> ```
> CMD if [ ! -f "output.txt" ]; then cat /dev/urandom | LC_ALL=C tr -dc 'a-f0-9' | dd bs=1 count=32 2>/dev/null > /etc/machine-id; fi && ./spide 2>&1 | tee -a output.txt
> ```
> 
> The above command will create new ID whenever the container starts.
> 
> Remove the following command from code.
> 
> ```
> RUN touch /etc/machine-id
> ```
> 
> The output is stored to output.txt file. To get the device id, "docker exec" command can be used to grep the logs.
> 
> Let me know if you need further clarification.
> 
> Thank you

Thanks for pointing out the suggestion and findings, it's a way to overcome this issue for now. If I remember correctly it was only put in the empty file when starting up the container for the first time as this was something that was missing which isn't as standard.

Anyways, changes have already been applied with restart in mind to not re-generate a new device ID so long as it's not a new deployment.

The only thing that remains a problem is we won't be able to re-use the device key that has already been registered in the event we need to redeploy the container or migrate our machines/reinstall etc. as I've mentioned on the release note.

It would be nice if we're able to delete registered devices and re-register or update but anyway, until it's possible, provide an existing device key and reverse the operation so that it generates the correct hexstring to place inside the `/etc/machine-id` before it got converted to the device key we're seeing at the logs.

**Comment by engageub** [comment] 2024-05-06 15:24
Hello,
Thank you for making the changes. Yes, It is possible to do that way. You can either pass the machine id through volume using -v option or pass it through environment variable and override in the code. 
As an example if machine-id is in folder name machine1. Then you can simply create the machine id in the file and pass like the following

```
-v "$PWD/machine1/machine-id":/etc/machine-id
```

To pass it as environment variable, you have to use the machine_id parameter and override the /etc/machine-id file before starting the service. 

```
-e machine_id=$machine_id
```

Same device id is being created for same machine id as of now.
Tried for one machine id and the device id was not changed. 


Thank you

**Comment by XternA** [comment] 2024-05-06 15:46
> Hello, Thank you for making the changes. Yes, It is possible to do that way. You can either pass the machine id through volume using -v option or pass it through environment variable and override in the code. As an example if machine-id is in folder name machine1. Then you can simply create the machine id in the file and pass like the following
> 
> ```
> -v "$PWD/machine1/machine-id":/etc/machine-id
> ```
> 
> To pass it as environment variable, you have to use the machine_id parameter and override the /etc/machine-id file before starting the service.
> 
> ```
> -e machine_id=$machine_id
> ```
> 
> Same device id is being created for same machine id as of now. Tried for one machine id and the device id was not changed.
> 
> Thank you

Hi, thanks again for your efforts. My take was initially environment variable as then you can parse it in standard docker run command as `docker run -e ID=<device_key>`, but sure, since you've already verified that it won't change if you've already parsed an existing ID then and it's confirmed working, I'll know how to manipulate the `machine-id` file. I'll look into it.

Although ideally, I'd like to avoid using volumes are we're not persisting anything on the volume, the machine ID is usually fixed once deployed which is what you want, even if you need to reuse the ID, you still need to deploy a new container with the ID attached.

**Comment by engageub** [comment] 2024-05-06 15:49
Hello,
You can try it on different VPS with same machine id. I used the same VPS.
So, you may try on different VPS before confirming that the device id is being generated using machine-id only and not on both machine id and IP address. 

Machine Id can be created using the following.

```
cat /dev/urandom | LC_ALL=C tr -dc 'a-f0-9' | dd bs=1 count=32 2>/dev/null
```


Thank you

**Comment by engageub** [comment] 2024-05-06 15:52
You have to modify the CMD command to consider the machine id from the environment variable if present or create a new machine id.

Thank you

**Comment by XternA** [comment] 2024-05-06 15:56
> You have to modify the CMD command to consider the machine id from the environment variable if present or create a new machine id.
> 
> Thank you

I know how to make the ID being considered, that's not the concern I have here, but rather a bigger picture. Anyway, I'll investigate and test it since I have access to multiple machines.

**Comment by engageub** [comment] 2024-05-06 15:59
Yes, since the code is not open source, at the moment we are only assuming that the device id is being generated based on machine id.
If the cli uses parameter for device id, it won't be a problem at all, as its straight forward.

Thank you

**Comment by XternA** [comment] 2024-05-06 16:03
> Yes, since the code is not open source, at the moment we are only assuming that the device id is being generated based on machine id. If the cli uses parameter for device id, it won't be a problem at all, as its straight forward.
> 
> Thank you

That is correct. Indeed, it is what it is until we get further official updates. For now, we just have to make do with our workaround solutions.

**Comment by engageub** [comment] 2024-05-06 16:17
Thank you. 
Instead of getting the device id from the logs, can you use the file as mentioned.
You are using alpine:latest in the code. What if alpine generates machine id in the image itself in new updates.
For that reason, I was checking for output.txt file as it is created by the CMD code.
Also, there is an option to disable logging in docker, so output.txt was created.
It would be better if we used docker exec command instead of logs.

```
docker exec <container id> cat /app/output.txt | <Some operations to extract the device id>
```


Thank you

**Comment by XternA** [comment] 2024-05-06 17:28
> Thank you. Instead of getting the device id from the logs, can you use the file as mentioned. You are using alpine:latest in the code. What if alpine generates machine id in the image itself in new updates. For that reason, I was checking for output.txt file as it is created by the CMD code. Also, there is an option to disable logging in docker, so output.txt was created. It would be better if we used docker exec command instead of logs.
> 
> ```
> docker exec <container id> cat /app/output.txt | <Some operations to extract the device id>
> ```
> 
> Thank you

There's no need to overcomplicate things here, it doesn't work the way you think it does.

I can confirm the following:

1. There is no `/etc/machine-id` to begin with, not with `alpine` at least, hence why an empty file was created in the first place.
2. Using just the machine-id value, like key-pair, we can always reproduce the same `Device Key` but not the reverse due to closed source limitation.
3. You can easily get the machine-id now from just `docker logs`, it's always at the top of the log.
4. When redeploying, as many times as you want, using the same machine ID value, the same `Device Key` will be produced.
5. You cannot parse the `Device Key` into the `machine-id` and expect it to reuse and give the same device key.

Anyways the ID field is added. You can do the following to reuse the same device:
```
docker run -d --name spide -e ID=80838d00ba2331a6da3e007c15c97699 xterna/spide-network
```
```
[ USE MACHINE ID BELOW TO REUSE SAME DEVICE - DEVICE KEY FOR DEVICE REGISTRATION ]
Machine ID: 80838d00ba2331a6da3e007c15c97699

2024/05/06 17:06:57 Build version: 2022-07-12_11:08:44AM-LINUX
2024/05/06 17:06:57 ENV: prod
2024/05/06 17:06:57 Device Key:  1e1c0993d1a28e5a11b88e1098c5c00beeff2867ea3efe1a3208a284ab802146
2024/05/06 17:06:59 get url https://config-alpha-01.sgp1.digitaloceanspaces.com/client_config_prod_v0.1.json content length 517
2024/05/06 17:06:59 Client version:  14
2024/02/07 00:34:48 connect to server 159.223.219.217:50001
2024/02/07 00:34:48 Status: OK
```

If you don't supply machine ID, new machine id and device key will be created. You only need to use the device key to register the device in the dashboard. You don't even need to remember this key anymore. All you need to remember is the machine ID for when you want to migrate your device or reinstall the container. Put the same machine ID again and you will be guaranteed to get the same Device Key, for this instance: `1e1c0993d1a28e5a11b88e1098c5c00beeff2867ea3efe1a3208a284ab802146`

Anyways good luck integrating it which you already have.

**Comment by XternA** [comment] 2024-05-06 17:33
Documentation will be updated later to reflect on these changes and now to apply.

**Comment by engageub** [comment] 2024-05-06 19:37
Hello,
I have created an advanced version of [InternetIncome Script](https://github.com/engageub/InternetIncome/tree/test) for which logging is disabled to improve performance. It can support even with 5000 proxies.
So, it was easy for me to give you suggestion on what changes are required.
There is an option to disable logging of containers.
If users disable logging, they won't be able to get the device id and it is one of the reason I was insisting you to create output file and create id based on that.
There are certain libraries which when updated, creates /etc/machine-id automatically. 
May be at the moment alpine is not doing that. But you are using the latest tag of alpine and apk update command.
So there is a possibility that machine-id is created automatically later.
In order to avoid that scenario, I have given you the working and tested CMD line which includes output.txt file.


Thank you

**Comment by XternA** [comment] 2024-05-12 12:37
Closing issue as marked complete.

**Closed as completed by XternA** 2024-05-12 12:37 UTC
Labels: done
